CONNECTAL_DIR ?= ../../../../connectal
INTERFACES = PmaTestRequest PmaTestIndication
BSVFILES = Top.bsv PmaTest.bsv ../../lib/bsv/Gearbox_66_40.bsv
CPPFILES = test_gearbox.cpp

#CONNECTALFLAGS += --bscflags="-show-elab-progress"

include $(CONNECTAL_DIR)/Makefile.connectal
