# TCL File Generated by Component Editor 14.0
# Sun Jan 25 19:52:30 EST 2015
# DO NOT MODIFY


# 
# mkEthPorts "mkEthPorts" v1.0
#  2015.01.25.19:52:30
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module mkEthPorts
# 
set_module_property DESCRIPTION ""
set_module_property NAME mkEthPorts
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mkEthPorts
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkEthPorts
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mkEthPorts.v VERILOG PATH de5/verilog/mkEthPorts.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avs
# 
add_interface avs avalon end
set_interface_property avs addressUnits WORDS
set_interface_property avs associatedClock clk_50
set_interface_property avs associatedReset rst_50
set_interface_property avs bitsPerSymbol 8
set_interface_property avs burstOnBurstBoundariesOnly false
set_interface_property avs burstcountUnits WORDS
set_interface_property avs explicitAddressSpan 0
set_interface_property avs holdTime 0
set_interface_property avs linewrapBursts false
set_interface_property avs maximumPendingReadTransactions 0
set_interface_property avs maximumPendingWriteTransactions 0
set_interface_property avs readLatency 0
set_interface_property avs readWaitTime 1
set_interface_property avs setupTime 0
set_interface_property avs timingUnits Cycles
set_interface_property avs writeWaitTime 0
set_interface_property avs ENABLED true
set_interface_property avs EXPORT_OF ""
set_interface_property avs PORT_NAME_MAP ""
set_interface_property avs CMSIS_SVD_VARIABLES ""
set_interface_property avs SVD_ADDRESS_GROUP ""

add_interface_port avs avs_s0_writedata writedata Input 32
add_interface_port avs avs_s0_address address Input 24
add_interface_port avs avs_s0_write write Input 1
add_interface_port avs avs_s0_read read Input 1
add_interface_port avs avs_s0_readdata readdata Output 32
add_interface_port avs avs_s0_waitrequest waitrequest Output 1
set_interface_assignment avs embeddedsw.configuration.isFlash 0
set_interface_assignment avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk_156
# 
add_interface clk_156 clock end
set_interface_property clk_156 clockRate 0
set_interface_property clk_156 ENABLED true
set_interface_property clk_156 EXPORT_OF ""
set_interface_property clk_156 PORT_NAME_MAP ""
set_interface_property clk_156 CMSIS_SVD_VARIABLES ""
set_interface_property clk_156 SVD_ADDRESS_GROUP ""

add_interface_port clk_156 CLK_clk_156_25 clk Input 1


# 
# connection point clk_644
# 
add_interface clk_644 clock end
set_interface_property clk_644 clockRate 0
set_interface_property clk_644 ENABLED true
set_interface_property clk_644 EXPORT_OF ""
set_interface_property clk_644 PORT_NAME_MAP ""
set_interface_property clk_644 CMSIS_SVD_VARIABLES ""
set_interface_property clk_644 SVD_ADDRESS_GROUP ""

add_interface_port clk_644 CLK_clk_644 clk Input 1


# 
# connection point rst_50
# 
add_interface rst_50 reset end
set_interface_property rst_50 associatedClock clk_50
set_interface_property rst_50 synchronousEdges DEASSERT
set_interface_property rst_50 ENABLED true
set_interface_property rst_50 EXPORT_OF ""
set_interface_property rst_50 PORT_NAME_MAP ""
set_interface_property rst_50 CMSIS_SVD_VARIABLES ""
set_interface_property rst_50 SVD_ADDRESS_GROUP ""

add_interface_port rst_50 RST_N_rst_50 reset_n Input 1


# 
# connection point clk_50
# 
add_interface clk_50 clock end
set_interface_property clk_50 clockRate 0
set_interface_property clk_50 ENABLED true
set_interface_property clk_50 EXPORT_OF ""
set_interface_property clk_50 PORT_NAME_MAP ""
set_interface_property clk_50 CMSIS_SVD_VARIABLES ""
set_interface_property clk_50 SVD_ADDRESS_GROUP ""

add_interface_port clk_50 CLK_clk_50 clk Input 1


# 
# connection point rst_156
# 
add_interface rst_156 reset end
set_interface_property rst_156 associatedClock clk_156
set_interface_property rst_156 synchronousEdges DEASSERT
set_interface_property rst_156 ENABLED true
set_interface_property rst_156 EXPORT_OF ""
set_interface_property rst_156 PORT_NAME_MAP ""
set_interface_property rst_156 CMSIS_SVD_VARIABLES ""
set_interface_property rst_156 SVD_ADDRESS_GROUP ""

add_interface_port rst_156 RST_N_rst_156_25 reset_n Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk_50
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset RST_N reset_n Input 1


# 
# connection point serial_0_tx_data
# 
add_interface serial_0_tx_data conduit end
set_interface_property serial_0_tx_data associatedClock ""
set_interface_property serial_0_tx_data associatedReset ""
set_interface_property serial_0_tx_data ENABLED true
set_interface_property serial_0_tx_data EXPORT_OF ""
set_interface_property serial_0_tx_data PORT_NAME_MAP ""
set_interface_property serial_0_tx_data CMSIS_SVD_VARIABLES ""
set_interface_property serial_0_tx_data SVD_ADDRESS_GROUP ""

add_interface_port serial_0_tx_data serial_0_tx_data serial_0_tx_data Output 1


# 
# connection point serial_0_rx_data
# 
add_interface serial_0_rx_data conduit end
set_interface_property serial_0_rx_data associatedClock ""
set_interface_property serial_0_rx_data associatedReset ""
set_interface_property serial_0_rx_data ENABLED true
set_interface_property serial_0_rx_data EXPORT_OF ""
set_interface_property serial_0_rx_data PORT_NAME_MAP ""
set_interface_property serial_0_rx_data CMSIS_SVD_VARIABLES ""
set_interface_property serial_0_rx_data SVD_ADDRESS_GROUP ""

add_interface_port serial_0_rx_data serial_0_rx_data serial_0_rx_data Input 1


# 
# connection point serial_1_tx_data
# 
add_interface serial_1_tx_data conduit end
set_interface_property serial_1_tx_data associatedClock ""
set_interface_property serial_1_tx_data associatedReset ""
set_interface_property serial_1_tx_data ENABLED true
set_interface_property serial_1_tx_data EXPORT_OF ""
set_interface_property serial_1_tx_data PORT_NAME_MAP ""
set_interface_property serial_1_tx_data CMSIS_SVD_VARIABLES ""
set_interface_property serial_1_tx_data SVD_ADDRESS_GROUP ""

add_interface_port serial_1_tx_data serial_1_tx_data serial_1_tx_data Output 1


# 
# connection point serial_1_rx_data
# 
add_interface serial_1_rx_data conduit end
set_interface_property serial_1_rx_data associatedClock ""
set_interface_property serial_1_rx_data associatedReset ""
set_interface_property serial_1_rx_data ENABLED true
set_interface_property serial_1_rx_data EXPORT_OF ""
set_interface_property serial_1_rx_data PORT_NAME_MAP ""
set_interface_property serial_1_rx_data CMSIS_SVD_VARIABLES ""
set_interface_property serial_1_rx_data SVD_ADDRESS_GROUP ""

add_interface_port serial_1_rx_data serial_1_rx_data serial_1_rx_data Input 1


# 
# connection point serial_3_tx_data
# 
add_interface serial_3_tx_data conduit end
set_interface_property serial_3_tx_data associatedClock ""
set_interface_property serial_3_tx_data associatedReset ""
set_interface_property serial_3_tx_data ENABLED true
set_interface_property serial_3_tx_data EXPORT_OF ""
set_interface_property serial_3_tx_data PORT_NAME_MAP ""
set_interface_property serial_3_tx_data CMSIS_SVD_VARIABLES ""
set_interface_property serial_3_tx_data SVD_ADDRESS_GROUP ""

add_interface_port serial_3_tx_data serial_3_tx_data serial_3_tx_data Output 1


# 
# connection point serial_2_rx_data
# 
add_interface serial_2_rx_data conduit end
set_interface_property serial_2_rx_data associatedClock ""
set_interface_property serial_2_rx_data associatedReset ""
set_interface_property serial_2_rx_data ENABLED true
set_interface_property serial_2_rx_data EXPORT_OF ""
set_interface_property serial_2_rx_data PORT_NAME_MAP ""
set_interface_property serial_2_rx_data CMSIS_SVD_VARIABLES ""
set_interface_property serial_2_rx_data SVD_ADDRESS_GROUP ""

add_interface_port serial_2_rx_data serial_2_rx_data serial_2_rx_data Input 1


# 
# connection point serial_2_tx_data
# 
add_interface serial_2_tx_data conduit end
set_interface_property serial_2_tx_data associatedClock ""
set_interface_property serial_2_tx_data associatedReset ""
set_interface_property serial_2_tx_data ENABLED true
set_interface_property serial_2_tx_data EXPORT_OF ""
set_interface_property serial_2_tx_data PORT_NAME_MAP ""
set_interface_property serial_2_tx_data CMSIS_SVD_VARIABLES ""
set_interface_property serial_2_tx_data SVD_ADDRESS_GROUP ""

add_interface_port serial_2_tx_data serial_2_tx_data serial_2_tx_data Output 1


# 
# connection point serial_3_rx_data
# 
add_interface serial_3_rx_data conduit end
set_interface_property serial_3_rx_data associatedClock ""
set_interface_property serial_3_rx_data associatedReset ""
set_interface_property serial_3_rx_data ENABLED true
set_interface_property serial_3_rx_data EXPORT_OF ""
set_interface_property serial_3_rx_data PORT_NAME_MAP ""
set_interface_property serial_3_rx_data CMSIS_SVD_VARIABLES ""
set_interface_property serial_3_rx_data SVD_ADDRESS_GROUP ""

add_interface_port serial_3_rx_data serial_3_rx_data serial_3_rx_data Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk CLK clk Input 1

