PCIE_TBED_VERILOG_FILES = \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/altera_primitives.v"                     \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/220model.v"                              \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/sgate.v"                                 \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/altera_mf.v"                             \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/altera_lnsim.sv"                         \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/stratixiv_hssi_atoms.v"                  \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/stratixiv_pcie_hip_atoms.v"              \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/stratixiv_atoms.v"                       \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/mentor/stratixv_atoms_ncrypt.v"          \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/stratixv_atoms.v"                        \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/mentor/stratixv_hssi_atoms_ncrypt.v"     \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/stratixv_hssi_atoms.v"                   \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/mentor/stratixv_pcie_hip_atoms_ncrypt.v" \
	"$(QUARTUS_INSTALL_DIR)/eda/sim_lib/stratixv_pcie_hip_atoms.v"               \
	"$(QSYS_SIMDIR)/simulation/submodules/verbosity_pkg.sv"                \
	"$(QSYS_SIMDIR)/simulation/submodules/altera_conduit_bfm.sv"           \
	"$(QSYS_SIMDIR)/simulation/submodules/altpcietb_ltssm_mon.v"           \
	"$(QSYS_SIMDIR)/simulation/submodules/altpcietb_pipe_phy.v"            \
	"$(QSYS_SIMDIR)/simulation/submodules/altpcietb_pipe32_hip_interface.v"\
	"$(QSYS_SIMDIR)/simulation/submodules/altpcietb_pipe32_driver.v"       \
	"$(QSYS_SIMDIR)/simulation/submodules/altpcie_tbed_sv_hwtcl.v"         \
	"$(QSYS_SIMDIR)/simulation/submodules/altpcietb_bfm_top_rp.v"          \
	"$(QSYS_SIMDIR)/simulation/submodules/altpcietb_bfm_rp_gen2_x8.v"      \
	"$(QSYS_SIMDIR)/simulation/submodules/altpcietb_bfm_driver_chaining.v" \
	"$(QSYS_SIMDIR)/simulation/submodules/altera_avalon_reset_source.sv"   \
	"$(QSYS_SIMDIR)/simulation/submodules/altera_avalon_clock_source.sv"   \
	"$(QSYS_SIMDIR)/simulation/pcie_tbed.v"

