CONNECTAL_DIR ?= ../../../../connectal
INTERFACES = PmaTestRequest PmaTestIndication
BSVFILES = Top.bsv PmaTest.bsv ../../lib/bsv/Gearbox_40_66.bsv
CPPFILES = test_gearbox.cpp

include $(CONNECTAL_DIR)/Makefile.connectal
